### PR TITLE
Trim SSD's

### PR DESCRIPTION
**Pull request by GuestSneezeOSDev**
* https://github.com/LukeShortCloud/winesapOS/issues/877 has been resolved

### CODE REVIEW

**Comment by GuestSneezeOSDev** [comment]
if you want to merge this delete the `<<<` `====` `>>>`

**Comment by GuestSneezeOSDev** [comment]
Close for now

**Comment by GuestSneezeOSDev** [comment]
https://github.com/LukeShortCloud/winesapOS/pull/922 Use this pull request instead

**Comment by LukeShortCloud** [comment]
Thanks for the PR! I pushed a bunch of changes recently which is why you're seeing some merge conflicts.

For the future, here are some steps to help you avoid having to delete and recreate your fork.

I recommend (1) adding my repository as a remote named "upstream" - yours will be "origin", (2) fetching the latest updates from "upstream" / winesapOS, (3) change to use the latest "main" branch, and then (4) checkout a new branch you can work on - optionally with the GitHub Issue number as the prefix.

```
$ git remote add upstream https://github.com/lukeshortcloud/winesapos.git
$ git fetch upstream
$ git checkout upstream/main
$ git checkout -b 877-trim-ssd
```

When you're done, you can  push your branch up and then submit a PR in GitHub.

```
$ git push origin 877-trim-ssd
```

It took me a long time to understand git. I'd be happy to help if you any questions or need any help with that. I've got some hints here in my notes that may also help:

https://rootpages.lukeshort.cloud/programming/devops.html#git-workflow

**Comment by GuestSneezeOSDev** [comment]
Thanks mate

**Pull request closed without merging**
