### PR TITLE
[WIP] git workflow with docker build

### PR DESCRIPTION
**Pull request by Thijzer**
[WIP]
https://github.com/LukeShortCloud/winesapOS/issues/155

continuation of closed PR https://github.com/LukeShortCloud/winesapOS/pull/310

Some file need to be removed or ignored before merge

### CODE REVIEW

**Comment by Thijzer** [comment]
@LukeShortCloud 
I have small question, I'm basing from archlinux:latest but in your installer you use a lot of binaries outside of the archlinux:latest.
We can always make our own base similar to the installer..

second question is this bug, i'm guessing it's that same binary issue. The winesapos.img file was created..
```
+scripts/winesapos-install.sh:47> fallocate -l 28G winesapos.img
+scripts/winesapos-install.sh:49> DEVICE=+scripts/winesapos-install.sh:49> losetup --partscan --find --show winesapos.img
losetup: winesapos.img: failed to set up loop device: No such file or directory
+scripts/winesapos-install.sh:49> DEVICE='' 
```

Sorry for the downtime, got sick :(

**Comment by LukeShortCloud** [comment]
Hey @Thijzer, that's okay and I hope you are feeling better! Glad to have your help on the project. :-) I'm also very busy this week so I'm sorry if my responses are delayed.

We have historically relied on what packages are provided on the Arch Linux, Manjaro, and SteamOS live environments which is usually a lot more than what the minimal `archlinux:latest` container providers. I like the idea of having our own container `winesapos-builder` or something similar. I'll take that as an action item to publish on Docker Hub.

I did some digging about that error. One possible problem is that the `loop` Linux kernel module is not loaded. I'm not sure if that's something we have control over in GitHub Actions. I don't think there is a way to load kernel modules from within a container. On the host, we need to run `modprobe loop`. https://github.com/RPi-Distro/pi-gen/issues/257

**Comment by LukeShortCloud** [comment]
I am very busy with work this week. This weekend I will look into setting up a virtual machine to use as a custom GitHub Actions runner. Having full control over the environment should really help out. We can then continue to use the Dockerfile and container approach to building and testing within the virtual machine.

**Comment by Thijzer** [comment]
Hey @LukeShortCloud, thanks for the help, I'm also investigating.
I think we have to transition the installer script from VM based to CT based as you can't use a lot those binaries like within the docker containers.
But building images can be done within a container, here is an example of chimeraOS doing it.
https://github.com/ChimeraOS/chimeraos/blob/master/build.sh 
https://github.com/ChimeraOS/chimeraos/blob/master/.github/workflows/main.yml

**Comment by LukeShortCloud** [comment]
Interesting, thanks for sharing! The biggest difference I see is that they do not create and use a partition table for the build image. We do. They also mount with the `loop` option but I am not sure if that requires the `loop` Linux kernel module to be loaded.

```
fallocate -l ${SIZE} ${BUILD_IMG}
mkfs.btrfs -f ${BUILD_IMG}
mount -t btrfs -o loop,nodatacow ${BUILD_IMG} ${MOUNT_PATH}
```

https://github.com/ChimeraOS/chimeraos/blob/9c5ad15cacdd10bcde9ed4ab3f3949b2374ceb1b/build.sh#L44-L46

**Comment by LukeShortCloud** [comment]
One other thing that is important to mention: using SteamOS the GitHub Actions environment is impossible right now. I need to create and publish a SteamOS container image. In the meantime, we can build the Arch Linux environment with this variable: `WINESAPOS_DISTRO=arch`.

**Comment by LukeShortCloud** [comment]
I made a base SteamOS container image and published it on Docker Hub. Long-term, I will change this to be under a different username. I will use this as a base to build a `winesapos-builder` image.

https://hub.docker.com/repository/docker/ekultails/steamos

**Comment by LukeShortCloud** [comment]
I modified your Dockerfile to use `ekultails/steamos:latest` and have been running the `test-build.sh` script. I'm still encountering the original error but I do have the `loop` kernel module loaded.

```
$ zsh test-build.sh
+scripts/winesapos-install.sh:47> DEVICE=+scripts/winesapos-install.sh:47> losetup --partscan --find --show winesapos.img
losetup: winesapos.img: failed to set up loop device: No such file or directory
```

```
$ lsmod | grep loop
loop                   40960  1
```

**Comment by LukeShortCloud** [comment]
Aha! I added this argument to the `docker run` command: `--cap-add MKNOD`. Now loop devices work.

https://serverfault.com/questions/701384/loop-device-in-a-linux-container

The next problem is that we still need to add more things to the build container such as additional file system support so that `mkfs.*` commands will work. There are probably lots of other missing things, too.

**Comment by LukeShortCloud** [comment]
Aha! I added this argument to the `docker run` command: `--cap-add MKNOD`. Now loop devices work.

https://serverfault.com/questions/701384/loop-device-in-a-linux-container

The next problem is that we still need to add more things to the build container such as additional file system support so that `mkfs.*` commands will work. There are probably lots of other missing things, too.

**Comment by LukeShortCloud** [comment]
I added these file system packages to the Dockerfile: `btrfs-progs dosfstools e2fsprogs exfatprogs`. The next problem is that there is a race-condition between when the loop back device partitions are created and then having them be loaded up. For example:

```
+scripts/winesapos-install.sh:81> mkfs -t exfat /dev/loop0p2
open failed : /dev/loop0p2, No such file or directory
exfatprogs version : 1.1.3

exFAT format fail!
```

But a `lsblk` ran from within the container about one second later reports that the loop devices are there.

```
$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0         7:0    0    28G  0 loop 
|-loop0p1   259:6    0     1M  0 part 
|-loop0p2   259:7    0  14.9G  0 part 
|-loop0p3   259:8    0   477M  0 part 
|-loop0p4   259:9    0   953M  0 part 
`-loop0p5   259:10   0  11.7G  0 part 
```

**Comment by LukeShortCloud** [comment]
I keep playing around with your branch and can't seem to get the build working in a container still. Instead, I have been focusing my energy on more preparation work towards a minimal image (not a container, but a new type of raw release image) which should be useful for CI purposes. I am going to be unavailable for the next couple of weeks. Once I'm back, I hope to soon re-visit this and just spend a whole weekend on figuring this out once and for all.

**Comment by LukeShortCloud** [comment]
Now that 3.1.0 has been released, this is my top priority again to get GitHub Actions working!

We now allow building without the 16 GB exFAT portable storage partition. This shrinks our image down to 13 GB which will help deal with GitHub Actions size limits. Related: https://github.com/LukeShortCloud/winesapOS/issues/426

I think I also figured out the problem with the loop device. Inside a container, the loop devices do not get updated but they do appear on the host. As a workaround, we can just mount the entire `/dev/` directory into the container. That should fix all of our problems (along with running the container as privileged for creating loop devices in the first place).

```
# https://github.com/moby/moby/issues/27886#issuecomment-257185319
$ sudo docker run -v /dev:/dev --privileged <OTHER_ARGS>
```

**Comment by LukeShortCloud** [comment]
@Thijzer I rebased your branch and have been making great progress with what you have started. Here are my latest commits:

https://github.com/LukeShortCloud/winesapOS/tree/gitflow-build-lukeshortcloud

**Comment by LukeShortCloud** [comment]
The latest issue is that something goes wrong with `udev` during the installation of the `zfs-dkms` package which causes future `chroot` commands to fail.

```
==> Finished making: zfs-dkms 2.1.5-1 (Wed Jul  6 23:53:41 2022)
==> Cleaning up...
loading packages...
resolving dependencies...
looking for conflicting packages...
Packages (1) zfs-dkms-2.1.5-1
Total Installed Size:  17.11 MiB
:: Proceed with installation? [Y/n] 
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
installing zfs-dkms...
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Install DKMS modules
==> Missing mandatory directory: /usr/lib/modules. Exiting!
error: command failed to execute correctly
umount: /winesapos/dev: target is busy.
+/workdir/scripts/winesapos-install.sh:395> echo -e 'apfs\nbtrfs\next4\nexfat\nfat\nhfs\nhfsplus\nntfs3\nzfs'
+/workdir/scripts/winesapos-install.sh:396> echo 'Installing additional file system support complete.'
Installing additional file system support complete.
+/workdir/scripts/winesapos-install.sh:398> echo 'Installing sound drivers...'
Installing sound drivers...
+/workdir/scripts/winesapos-install.sh:401> arch-chroot /winesapos /usr/bin/pacman --noconfirm -S --needed pipewire lib32-pipewire pipewire-media-session
mount: /winesapos/dev: udev already mounted on /winesapos/dev.
       dmesg(1) may have more information after failed mount system call.
==> ERROR: failed to setup chroot /winesapos
```

**Comment by LukeShortCloud** [comment]
@Thijzer GitHub Actions works thanks to you! Here is our first successful job: https://github.com/LukeShortCloud/winesapOS/actions/runs/2686204120 .

I will go ahead and merge this. I made a separate branch to make a few minor tweaks rebased on-top of your original work here. I'll close out this pull request and your commits will now be in the main branch.

**Pull request closed without merging**
