### PR TITLE
Added more apps follow up

### PR DESCRIPTION
**Pull request by LukeShortCloud**

### CODE REVIEW

**Comment by LukeShortCloud** [comment]
The only thing I have not fully addressed yet is Waydroid support. That needs more testing before I can get it fully integrated into winesapOS.

**Comment by LukeShortCloud** [comment]
Waydroid packages are already provided by the Chaotic AUR repository. `waydroid-image` and `waydroid-image-gapps` conflict. Installing these two required packages `waydroid waydroid-image-gapps` takes 2.5 GiB of installed space. This needs to be part of the first-time setup and not the image build due to the huge size.

**Comment by GuestSneezeOSDev** [comment]
Maybe we do not require google apps support

**Comment by LukeShortCloud** [comment]
That's okay, `waydroid` is useless without having the related `waydroid-image` to launch.

I was testing this out and it works great! All I had to do (after going the winesapOS first-time setup and selecting to install Waydroid) was to: (1) launch "Waydroid" and tell it to initialize the "GAPPS" variant and then (2) run `waydroid show-full-ui`. It ran as a windowed full-screen desktop.

@GuestSneezeOSDev The files you originally added seemed to be for getting a Waydroid session to work (running Waydroid without a desktop environment). I could not get that to work so I'll drop those related files/services for now and maybe we can revisit that later if you want. When running `waydroid show-full-ui`, it automatically starts all of the necessary services for it to run.

**Comment by LukeShortCloud** [comment]
I'm going to merge this in. Separately, I'll follow-up with some tweaks to the `winesapos-dual-boot.sh` script. Right now, it's just a copy and paste of the documentation except it's hard-coded to use `/dev/sdb` for EFI (which will be different on each system and should also be a partition and not a device). We can do some fancy things like automatically detect the EFI partition, maybe find the new partition to use as the root partition, show the user the list of drives that are available to use, etc.

Long-term, I'd like to write a very advanced dual-boot installer in Rust but what we have right now is available today and mostly working!

**Pull request merged**
